@startjson
{
  "止": {
    "走":{"赵":{}, "趋":{}, "赴":{}},
    "武":{"赋":{}, "斌":{}},    
    "足":{
        "捉":{},
        "促":{},
        "浞":{}
    },
    "步":{"埗":{},"踄":{}},
    "齿":{"啮":{}},
    "企":{},
    "此":{"眦":{}, "些":{}},
    "耻":{},
    "歧":{}
  }
}
@endjson
